// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: city_game_proto.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

/////////////////// Enums ///////////////////
type Building int32

const (
	Building_Workbench Building = 0
	Building_Furnace   Building = 1
	Building_Lumber    Building = 2
	Building_Stonepile Building = 3
	Building_Mine      Building = 4
	Building_Sandpit   Building = 5
	Building_Crate     Building = 6
	Building_House     Building = 7
)

// Enum value maps for Building.
var (
	Building_name = map[int32]string{
		0: "Workbench",
		1: "Furnace",
		2: "Lumber",
		3: "Stonepile",
		4: "Mine",
		5: "Sandpit",
		6: "Crate",
		7: "House",
	}
	Building_value = map[string]int32{
		"Workbench": 0,
		"Furnace":   1,
		"Lumber":    2,
		"Stonepile": 3,
		"Mine":      4,
		"Sandpit":   5,
		"Crate":     6,
		"House":     7,
	}
)

func (x Building) Enum() *Building {
	p := new(Building)
	*p = x
	return p
}

func (x Building) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Building) Descriptor() protoreflect.EnumDescriptor {
	return file_city_game_proto_proto_enumTypes[0].Descriptor()
}

func (Building) Type() protoreflect.EnumType {
	return &file_city_game_proto_proto_enumTypes[0]
}

func (x Building) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Building.Descriptor instead.
func (Building) EnumDescriptor() ([]byte, []int) {
	return file_city_game_proto_proto_rawDescGZIP(), []int{0}
}

type Item int32

const (
	Item_Pickaxe    Item = 0
	Item_Bucket     Item = 1
	Item_Plank      Item = 2
	Item_Stone      Item = 3
	Item_Ore        Item = 4
	Item_SandBucket Item = 5
	Item_Glass      Item = 6
	Item_Metal      Item = 7
	Item_Window     Item = 8
	Item_Door       Item = 9
	Item_IWorkbench Item = 10
	Item_IFurnace   Item = 11
	Item_ICrate     Item = 12
)

// Enum value maps for Item.
var (
	Item_name = map[int32]string{
		0:  "Pickaxe",
		1:  "Bucket",
		2:  "Plank",
		3:  "Stone",
		4:  "Ore",
		5:  "SandBucket",
		6:  "Glass",
		7:  "Metal",
		8:  "Window",
		9:  "Door",
		10: "IWorkbench",
		11: "IFurnace",
		12: "ICrate",
	}
	Item_value = map[string]int32{
		"Pickaxe":    0,
		"Bucket":     1,
		"Plank":      2,
		"Stone":      3,
		"Ore":        4,
		"SandBucket": 5,
		"Glass":      6,
		"Metal":      7,
		"Window":     8,
		"Door":       9,
		"IWorkbench": 10,
		"IFurnace":   11,
		"ICrate":     12,
	}
)

func (x Item) Enum() *Item {
	p := new(Item)
	*p = x
	return p
}

func (x Item) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Item) Descriptor() protoreflect.EnumDescriptor {
	return file_city_game_proto_proto_enumTypes[1].Descriptor()
}

func (Item) Type() protoreflect.EnumType {
	return &file_city_game_proto_proto_enumTypes[1]
}

func (x Item) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Item.Descriptor instead.
func (Item) EnumDescriptor() ([]byte, []int) {
	return file_city_game_proto_proto_rawDescGZIP(), []int{1}
}

// Sorted in priority order
type ActionType int32

const (
	ActionType_A_Nothing ActionType = 0
	ActionType_Place     ActionType = 1
	ActionType_Give      ActionType = 2
	ActionType_Take      ActionType = 3
	ActionType_Interact  ActionType = 4
	ActionType_Push      ActionType = 5
	ActionType_Walk      ActionType = 6
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "A_Nothing",
		1: "Place",
		2: "Give",
		3: "Take",
		4: "Interact",
		5: "Push",
		6: "Walk",
	}
	ActionType_value = map[string]int32{
		"A_Nothing": 0,
		"Place":     1,
		"Give":      2,
		"Take":      3,
		"Interact":  4,
		"Push":      5,
		"Walk":      6,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_city_game_proto_proto_enumTypes[2].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_city_game_proto_proto_enumTypes[2]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_city_game_proto_proto_rawDescGZIP(), []int{2}
}

type NecromancerActionType int32

const (
	NecromancerActionType_N_Nothing NecromancerActionType = 0
	NecromancerActionType_Summon    NecromancerActionType = 1
	NecromancerActionType_Release   NecromancerActionType = 2
)

// Enum value maps for NecromancerActionType.
var (
	NecromancerActionType_name = map[int32]string{
		0: "N_Nothing",
		1: "Summon",
		2: "Release",
	}
	NecromancerActionType_value = map[string]int32{
		"N_Nothing": 0,
		"Summon":    1,
		"Release":   2,
	}
)

func (x NecromancerActionType) Enum() *NecromancerActionType {
	p := new(NecromancerActionType)
	*p = x
	return p
}

func (x NecromancerActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NecromancerActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_city_game_proto_proto_enumTypes[3].Descriptor()
}

func (NecromancerActionType) Type() protoreflect.EnumType {
	return &file_city_game_proto_proto_enumTypes[3]
}

func (x NecromancerActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NecromancerActionType.Descriptor instead.
func (NecromancerActionType) EnumDescriptor() ([]byte, []int) {
	return file_city_game_proto_proto_rawDescGZIP(), []int{3}
}

type Direction int32

const (
	Direction_Up    Direction = 0
	Direction_Right Direction = 1
	Direction_Down  Direction = 2
	Direction_Left  Direction = 3
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "Up",
		1: "Right",
		2: "Down",
		3: "Left",
	}
	Direction_value = map[string]int32{
		"Up":    0,
		"Right": 1,
		"Down":  2,
		"Left":  3,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_city_game_proto_proto_enumTypes[4].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_city_game_proto_proto_enumTypes[4]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_city_game_proto_proto_rawDescGZIP(), []int{4}
}

/////////////////// Support Messages ///////////////////
type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             uint32                 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint32                 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_city_game_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_city_game_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_city_game_proto_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinate) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Coordinate) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Stack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        Item                   `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3,enum=city_game.Item" json:"item_id,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stack) Reset() {
	*x = Stack{}
	mi := &file_city_game_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stack) ProtoMessage() {}

func (x *Stack) ProtoReflect() protoreflect.Message {
	mi := &file_city_game_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stack.ProtoReflect.Descriptor instead.
func (*Stack) Descriptor() ([]byte, []int) {
	return file_city_game_proto_proto_rawDescGZIP(), []int{1}
}

func (x *Stack) GetItemId() Item {
	if x != nil {
		return x.ItemId
	}
	return Item_Pickaxe
}

func (x *Stack) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ItemRequirement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        Item                   `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3,enum=city_game.Item" json:"item_id,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Total         uint32                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRequirement) Reset() {
	*x = ItemRequirement{}
	mi := &file_city_game_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRequirement) ProtoMessage() {}

func (x *ItemRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_city_game_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRequirement.ProtoReflect.Descriptor instead.
func (*ItemRequirement) Descriptor() ([]byte, []int) {
	return file_city_game_proto_proto_rawDescGZIP(), []int{2}
}

func (x *ItemRequirement) GetItemId() Item {
	if x != nil {
		return x.ItemId
	}
	return Item_Pickaxe
}

func (x *ItemRequirement) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ItemRequirement) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinate    *Coordinate            `protobuf:"bytes,1,opt,name=coordinate,proto3,oneof" json:"coordinate,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_city_game_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_city_game_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_city_game_proto_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorMessage) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

/////////////////// Messages ///////////////////
type BuildingState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildingType  Building               `protobuf:"varint,1,opt,name=building_type,json=buildingType,proto3,enum=city_game.Building" json:"building_type,omitempty"`
	Coordinate    *Coordinate            `protobuf:"bytes,2,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	Items         []*Stack               `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	State         uint32                 `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildingState) Reset() {
	*x = BuildingState{}
	mi := &file_city_game_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildingState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingState) ProtoMessage() {}

func (x *BuildingState) ProtoReflect() protoreflect.Message {
	mi := &file_city_game_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingState.ProtoReflect.Descriptor instead.
func (*BuildingState) Descriptor() ([]byte, []int) {
	return file_city_game_proto_proto_rawDescGZIP(), []int{4}
}

func (x *BuildingState) GetBuildingType() Building {
	if x != nil {
		return x.BuildingType
	}
	return Building_Workbench
}

func (x *BuildingState) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *BuildingState) GetItems() []*Stack {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BuildingState) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionType    ActionType             `protobuf:"varint,1,opt,name=action_type,json=actionType,proto3,enum=city_game.ActionType" json:"action_type,omitempty"`
	Direction     *Direction             `protobuf:"varint,2,opt,name=direction,proto3,enum=city_game.Direction,oneof" json:"direction,omitempty"`
	Coordinate    *Coordinate            `protobuf:"bytes,3,opt,name=coordinate,proto3,oneof" json:"coordinate,omitempty"`
	ItemId        *Item                  `protobuf:"varint,4,opt,name=item_id,json=itemId,proto3,enum=city_game.Item,oneof" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_city_game_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_city_game_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_city_game_proto_proto_rawDescGZIP(), []int{5}
}

func (x *Action) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_A_Nothing
}

func (x *Action) GetDirection() Direction {
	if x != nil && x.Direction != nil {
		return *x.Direction
	}
	return Direction_Up
}

func (x *Action) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *Action) GetItemId() Item {
	if x != nil && x.ItemId != nil {
		return *x.ItemId
	}
	return Item_Pickaxe
}

type NecromancerAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionType    NecromancerActionType  `protobuf:"varint,1,opt,name=action_type,json=actionType,proto3,enum=city_game.NecromancerActionType" json:"action_type,omitempty"`
	Coordinate    *Coordinate            `protobuf:"bytes,2,opt,name=coordinate,proto3,oneof" json:"coordinate,omitempty"`
	HelperId      *uint32                `protobuf:"varint,3,opt,name=helper_id,json=helperId,proto3,oneof" json:"helper_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NecromancerAction) Reset() {
	*x = NecromancerAction{}
	mi := &file_city_game_proto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NecromancerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NecromancerAction) ProtoMessage() {}

func (x *NecromancerAction) ProtoReflect() protoreflect.Message {
	mi := &file_city_game_proto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NecromancerAction.ProtoReflect.Descriptor instead.
func (*NecromancerAction) Descriptor() ([]byte, []int) {
	return file_city_game_proto_proto_rawDescGZIP(), []int{6}
}

func (x *NecromancerAction) GetActionType() NecromancerActionType {
	if x != nil {
		return x.ActionType
	}
	return NecromancerActionType_N_Nothing
}

func (x *NecromancerAction) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *NecromancerAction) GetHelperId() uint32 {
	if x != nil && x.HelperId != nil {
		return *x.HelperId
	}
	return 0
}

type HelperState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HelperId      uint32                 `protobuf:"varint,1,opt,name=helper_id,json=helperId,proto3" json:"helper_id,omitempty"`
	Coordinate    *Coordinate            `protobuf:"bytes,2,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	Items         []*Stack               `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Action        *Action                `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelperState) Reset() {
	*x = HelperState{}
	mi := &file_city_game_proto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelperState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelperState) ProtoMessage() {}

func (x *HelperState) ProtoReflect() protoreflect.Message {
	mi := &file_city_game_proto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelperState.ProtoReflect.Descriptor instead.
func (*HelperState) Descriptor() ([]byte, []int) {
	return file_city_game_proto_proto_rawDescGZIP(), []int{7}
}

func (x *HelperState) GetHelperId() uint32 {
	if x != nil {
		return x.HelperId
	}
	return 0
}

func (x *HelperState) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *HelperState) GetItems() []*Stack {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *HelperState) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

type CraftingRecipe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requirements  []*Stack               `protobuf:"bytes,1,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Result        Item                   `protobuf:"varint,2,opt,name=result,proto3,enum=city_game.Item" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CraftingRecipe) Reset() {
	*x = CraftingRecipe{}
	mi := &file_city_game_proto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CraftingRecipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CraftingRecipe) ProtoMessage() {}

func (x *CraftingRecipe) ProtoReflect() protoreflect.Message {
	mi := &file_city_game_proto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CraftingRecipe.ProtoReflect.Descriptor instead.
func (*CraftingRecipe) Descriptor() ([]byte, []int) {
	return file_city_game_proto_proto_rawDescGZIP(), []int{8}
}

func (x *CraftingRecipe) GetRequirements() []*Stack {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *CraftingRecipe) GetResult() Item {
	if x != nil {
		return x.Result
	}
	return Item_Pickaxe
}

type HelperInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HelperId      uint32                 `protobuf:"varint,1,opt,name=helper_id,json=helperId,proto3" json:"helper_id,omitempty"`
	Action        *Action                `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelperInput) Reset() {
	*x = HelperInput{}
	mi := &file_city_game_proto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelperInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelperInput) ProtoMessage() {}

func (x *HelperInput) ProtoReflect() protoreflect.Message {
	mi := &file_city_game_proto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelperInput.ProtoReflect.Descriptor instead.
func (*HelperInput) Descriptor() ([]byte, []int) {
	return file_city_game_proto_proto_rawDescGZIP(), []int{9}
}

func (x *HelperInput) GetHelperId() uint32 {
	if x != nil {
		return x.HelperId
	}
	return 0
}

func (x *HelperInput) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

type GameState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Tick              uint32                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Mana              uint32                 `protobuf:"varint,2,opt,name=mana,proto3" json:"mana,omitempty"`
	Layer             uint32                 `protobuf:"varint,3,opt,name=layer,proto3" json:"layer,omitempty"`
	LayerRequirements []*ItemRequirement     `protobuf:"bytes,4,rep,name=layer_requirements,json=layerRequirements,proto3" json:"layer_requirements,omitempty"`
	BuildingStates    []*BuildingState       `protobuf:"bytes,5,rep,name=building_states,json=buildingStates,proto3" json:"building_states,omitempty"`
	HelperStates      []*HelperState         `protobuf:"bytes,6,rep,name=helper_states,json=helperStates,proto3" json:"helper_states,omitempty"`
	ErrorMessages     []*ErrorMessage        `protobuf:"bytes,7,rep,name=error_messages,json=errorMessages,proto3" json:"error_messages,omitempty"`
	GameId            string                 `protobuf:"bytes,8,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_city_game_proto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_city_game_proto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_city_game_proto_proto_rawDescGZIP(), []int{10}
}

func (x *GameState) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *GameState) GetMana() uint32 {
	if x != nil {
		return x.Mana
	}
	return 0
}

func (x *GameState) GetLayer() uint32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *GameState) GetLayerRequirements() []*ItemRequirement {
	if x != nil {
		return x.LayerRequirements
	}
	return nil
}

func (x *GameState) GetBuildingStates() []*BuildingState {
	if x != nil {
		return x.BuildingStates
	}
	return nil
}

func (x *GameState) GetHelperStates() []*HelperState {
	if x != nil {
		return x.HelperStates
	}
	return nil
}

func (x *GameState) GetErrorMessages() []*ErrorMessage {
	if x != nil {
		return x.ErrorMessages
	}
	return nil
}

func (x *GameState) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GameInput struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NecromancerAction *NecromancerAction     `protobuf:"bytes,1,opt,name=necromancer_action,json=necromancerAction,proto3" json:"necromancer_action,omitempty"`
	HelperInput       []*HelperInput         `protobuf:"bytes,2,rep,name=helper_input,json=helperInput,proto3" json:"helper_input,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GameInput) Reset() {
	*x = GameInput{}
	mi := &file_city_game_proto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInput) ProtoMessage() {}

func (x *GameInput) ProtoReflect() protoreflect.Message {
	mi := &file_city_game_proto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInput.ProtoReflect.Descriptor instead.
func (*GameInput) Descriptor() ([]byte, []int) {
	return file_city_game_proto_proto_rawDescGZIP(), []int{11}
}

func (x *GameInput) GetNecromancerAction() *NecromancerAction {
	if x != nil {
		return x.NecromancerAction
	}
	return nil
}

func (x *GameInput) GetHelperInput() []*HelperInput {
	if x != nil {
		return x.HelperInput
	}
	return nil
}

type TickData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *GameState             `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Input         *GameInput             `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickData) Reset() {
	*x = TickData{}
	mi := &file_city_game_proto_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickData) ProtoMessage() {}

func (x *TickData) ProtoReflect() protoreflect.Message {
	mi := &file_city_game_proto_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickData.ProtoReflect.Descriptor instead.
func (*TickData) Descriptor() ([]byte, []int) {
	return file_city_game_proto_proto_rawDescGZIP(), []int{12}
}

func (x *TickData) GetState() *GameState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *TickData) GetInput() *GameInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type GameData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*TickData            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameData) Reset() {
	*x = GameData{}
	mi := &file_city_game_proto_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameData) ProtoMessage() {}

func (x *GameData) ProtoReflect() protoreflect.Message {
	mi := &file_city_game_proto_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameData.ProtoReflect.Descriptor instead.
func (*GameData) Descriptor() ([]byte, []int) {
	return file_city_game_proto_proto_rawDescGZIP(), []int{13}
}

func (x *GameData) GetData() []*TickData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_city_game_proto_proto protoreflect.FileDescriptor

const file_city_game_proto_proto_rawDesc = "" +
	"\n" +
	"\x15city_game_proto.proto\x12\tcity_game\"(\n" +
	"\n" +
	"Coordinate\x12\f\n" +
	"\x01x\x18\x01 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\rR\x01y\"G\n" +
	"\x05Stack\x12(\n" +
	"\aitem_id\x18\x01 \x01(\x0e2\x0f.city_game.ItemR\x06itemId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"g\n" +
	"\x0fItemRequirement\x12(\n" +
	"\aitem_id\x18\x01 \x01(\x0e2\x0f.city_game.ItemR\x06itemId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x14\n" +
	"\x05total\x18\x03 \x01(\rR\x05total\"s\n" +
	"\fErrorMessage\x12:\n" +
	"\n" +
	"coordinate\x18\x01 \x01(\v2\x15.city_game.CoordinateH\x00R\n" +
	"coordinate\x88\x01\x01\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\r\n" +
	"\v_coordinate\"\xbe\x01\n" +
	"\rBuildingState\x128\n" +
	"\rbuilding_type\x18\x01 \x01(\x0e2\x13.city_game.BuildingR\fbuildingType\x125\n" +
	"\n" +
	"coordinate\x18\x02 \x01(\v2\x15.city_game.CoordinateR\n" +
	"coordinate\x12&\n" +
	"\x05items\x18\x03 \x03(\v2\x10.city_game.StackR\x05items\x12\x14\n" +
	"\x05state\x18\x04 \x01(\rR\x05state\"\x8d\x02\n" +
	"\x06Action\x126\n" +
	"\vaction_type\x18\x01 \x01(\x0e2\x15.city_game.ActionTypeR\n" +
	"actionType\x127\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x14.city_game.DirectionH\x00R\tdirection\x88\x01\x01\x12:\n" +
	"\n" +
	"coordinate\x18\x03 \x01(\v2\x15.city_game.CoordinateH\x01R\n" +
	"coordinate\x88\x01\x01\x12-\n" +
	"\aitem_id\x18\x04 \x01(\x0e2\x0f.city_game.ItemH\x02R\x06itemId\x88\x01\x01B\f\n" +
	"\n" +
	"_directionB\r\n" +
	"\v_coordinateB\n" +
	"\n" +
	"\b_item_id\"\xd1\x01\n" +
	"\x11NecromancerAction\x12A\n" +
	"\vaction_type\x18\x01 \x01(\x0e2 .city_game.NecromancerActionTypeR\n" +
	"actionType\x12:\n" +
	"\n" +
	"coordinate\x18\x02 \x01(\v2\x15.city_game.CoordinateH\x00R\n" +
	"coordinate\x88\x01\x01\x12 \n" +
	"\thelper_id\x18\x03 \x01(\rH\x01R\bhelperId\x88\x01\x01B\r\n" +
	"\v_coordinateB\f\n" +
	"\n" +
	"_helper_id\"\xb4\x01\n" +
	"\vHelperState\x12\x1b\n" +
	"\thelper_id\x18\x01 \x01(\rR\bhelperId\x125\n" +
	"\n" +
	"coordinate\x18\x02 \x01(\v2\x15.city_game.CoordinateR\n" +
	"coordinate\x12&\n" +
	"\x05items\x18\x03 \x03(\v2\x10.city_game.StackR\x05items\x12)\n" +
	"\x06action\x18\x04 \x01(\v2\x11.city_game.ActionR\x06action\"o\n" +
	"\x0eCraftingRecipe\x124\n" +
	"\frequirements\x18\x01 \x03(\v2\x10.city_game.StackR\frequirements\x12'\n" +
	"\x06result\x18\x02 \x01(\x0e2\x0f.city_game.ItemR\x06result\"U\n" +
	"\vHelperInput\x12\x1b\n" +
	"\thelper_id\x18\x01 \x01(\rR\bhelperId\x12)\n" +
	"\x06action\x18\x02 \x01(\v2\x11.city_game.ActionR\x06action\"\xed\x02\n" +
	"\tGameState\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick\x12\x12\n" +
	"\x04mana\x18\x02 \x01(\rR\x04mana\x12\x14\n" +
	"\x05layer\x18\x03 \x01(\rR\x05layer\x12I\n" +
	"\x12layer_requirements\x18\x04 \x03(\v2\x1a.city_game.ItemRequirementR\x11layerRequirements\x12A\n" +
	"\x0fbuilding_states\x18\x05 \x03(\v2\x18.city_game.BuildingStateR\x0ebuildingStates\x12;\n" +
	"\rhelper_states\x18\x06 \x03(\v2\x16.city_game.HelperStateR\fhelperStates\x12>\n" +
	"\x0eerror_messages\x18\a \x03(\v2\x17.city_game.ErrorMessageR\rerrorMessages\x12\x17\n" +
	"\agame_id\x18\b \x01(\tR\x06gameId\"\x93\x01\n" +
	"\tGameInput\x12K\n" +
	"\x12necromancer_action\x18\x01 \x01(\v2\x1c.city_game.NecromancerActionR\x11necromancerAction\x129\n" +
	"\fhelper_input\x18\x02 \x03(\v2\x16.city_game.HelperInputR\vhelperInput\"b\n" +
	"\bTickData\x12*\n" +
	"\x05state\x18\x01 \x01(\v2\x14.city_game.GameStateR\x05state\x12*\n" +
	"\x05input\x18\x02 \x01(\v2\x14.city_game.GameInputR\x05input\"3\n" +
	"\bGameData\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.city_game.TickDataR\x04data*n\n" +
	"\bBuilding\x12\r\n" +
	"\tWorkbench\x10\x00\x12\v\n" +
	"\aFurnace\x10\x01\x12\n" +
	"\n" +
	"\x06Lumber\x10\x02\x12\r\n" +
	"\tStonepile\x10\x03\x12\b\n" +
	"\x04Mine\x10\x04\x12\v\n" +
	"\aSandpit\x10\x05\x12\t\n" +
	"\x05Crate\x10\x06\x12\t\n" +
	"\x05House\x10\a*\xa4\x01\n" +
	"\x04Item\x12\v\n" +
	"\aPickaxe\x10\x00\x12\n" +
	"\n" +
	"\x06Bucket\x10\x01\x12\t\n" +
	"\x05Plank\x10\x02\x12\t\n" +
	"\x05Stone\x10\x03\x12\a\n" +
	"\x03Ore\x10\x04\x12\x0e\n" +
	"\n" +
	"SandBucket\x10\x05\x12\t\n" +
	"\x05Glass\x10\x06\x12\t\n" +
	"\x05Metal\x10\a\x12\n" +
	"\n" +
	"\x06Window\x10\b\x12\b\n" +
	"\x04Door\x10\t\x12\x0e\n" +
	"\n" +
	"IWorkbench\x10\n" +
	"\x12\f\n" +
	"\bIFurnace\x10\v\x12\n" +
	"\n" +
	"\x06ICrate\x10\f*\\\n" +
	"\n" +
	"ActionType\x12\r\n" +
	"\tA_Nothing\x10\x00\x12\t\n" +
	"\x05Place\x10\x01\x12\b\n" +
	"\x04Give\x10\x02\x12\b\n" +
	"\x04Take\x10\x03\x12\f\n" +
	"\bInteract\x10\x04\x12\b\n" +
	"\x04Push\x10\x05\x12\b\n" +
	"\x04Walk\x10\x06*?\n" +
	"\x15NecromancerActionType\x12\r\n" +
	"\tN_Nothing\x10\x00\x12\n" +
	"\n" +
	"\x06Summon\x10\x01\x12\v\n" +
	"\aRelease\x10\x02*2\n" +
	"\tDirection\x12\x06\n" +
	"\x02Up\x10\x00\x12\t\n" +
	"\x05Right\x10\x01\x12\b\n" +
	"\x04Down\x10\x02\x12\b\n" +
	"\x04Left\x10\x03B\x12Z\x10../server/src/pbb\x06proto3"

var (
	file_city_game_proto_proto_rawDescOnce sync.Once
	file_city_game_proto_proto_rawDescData []byte
)

func file_city_game_proto_proto_rawDescGZIP() []byte {
	file_city_game_proto_proto_rawDescOnce.Do(func() {
		file_city_game_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_city_game_proto_proto_rawDesc), len(file_city_game_proto_proto_rawDesc)))
	})
	return file_city_game_proto_proto_rawDescData
}

var file_city_game_proto_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_city_game_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_city_game_proto_proto_goTypes = []any{
	(Building)(0),              // 0: city_game.Building
	(Item)(0),                  // 1: city_game.Item
	(ActionType)(0),            // 2: city_game.ActionType
	(NecromancerActionType)(0), // 3: city_game.NecromancerActionType
	(Direction)(0),             // 4: city_game.Direction
	(*Coordinate)(nil),         // 5: city_game.Coordinate
	(*Stack)(nil),              // 6: city_game.Stack
	(*ItemRequirement)(nil),    // 7: city_game.ItemRequirement
	(*ErrorMessage)(nil),       // 8: city_game.ErrorMessage
	(*BuildingState)(nil),      // 9: city_game.BuildingState
	(*Action)(nil),             // 10: city_game.Action
	(*NecromancerAction)(nil),  // 11: city_game.NecromancerAction
	(*HelperState)(nil),        // 12: city_game.HelperState
	(*CraftingRecipe)(nil),     // 13: city_game.CraftingRecipe
	(*HelperInput)(nil),        // 14: city_game.HelperInput
	(*GameState)(nil),          // 15: city_game.GameState
	(*GameInput)(nil),          // 16: city_game.GameInput
	(*TickData)(nil),           // 17: city_game.TickData
	(*GameData)(nil),           // 18: city_game.GameData
}
var file_city_game_proto_proto_depIdxs = []int32{
	1,  // 0: city_game.Stack.item_id:type_name -> city_game.Item
	1,  // 1: city_game.ItemRequirement.item_id:type_name -> city_game.Item
	5,  // 2: city_game.ErrorMessage.coordinate:type_name -> city_game.Coordinate
	0,  // 3: city_game.BuildingState.building_type:type_name -> city_game.Building
	5,  // 4: city_game.BuildingState.coordinate:type_name -> city_game.Coordinate
	6,  // 5: city_game.BuildingState.items:type_name -> city_game.Stack
	2,  // 6: city_game.Action.action_type:type_name -> city_game.ActionType
	4,  // 7: city_game.Action.direction:type_name -> city_game.Direction
	5,  // 8: city_game.Action.coordinate:type_name -> city_game.Coordinate
	1,  // 9: city_game.Action.item_id:type_name -> city_game.Item
	3,  // 10: city_game.NecromancerAction.action_type:type_name -> city_game.NecromancerActionType
	5,  // 11: city_game.NecromancerAction.coordinate:type_name -> city_game.Coordinate
	5,  // 12: city_game.HelperState.coordinate:type_name -> city_game.Coordinate
	6,  // 13: city_game.HelperState.items:type_name -> city_game.Stack
	10, // 14: city_game.HelperState.action:type_name -> city_game.Action
	6,  // 15: city_game.CraftingRecipe.requirements:type_name -> city_game.Stack
	1,  // 16: city_game.CraftingRecipe.result:type_name -> city_game.Item
	10, // 17: city_game.HelperInput.action:type_name -> city_game.Action
	7,  // 18: city_game.GameState.layer_requirements:type_name -> city_game.ItemRequirement
	9,  // 19: city_game.GameState.building_states:type_name -> city_game.BuildingState
	12, // 20: city_game.GameState.helper_states:type_name -> city_game.HelperState
	8,  // 21: city_game.GameState.error_messages:type_name -> city_game.ErrorMessage
	11, // 22: city_game.GameInput.necromancer_action:type_name -> city_game.NecromancerAction
	14, // 23: city_game.GameInput.helper_input:type_name -> city_game.HelperInput
	15, // 24: city_game.TickData.state:type_name -> city_game.GameState
	16, // 25: city_game.TickData.input:type_name -> city_game.GameInput
	17, // 26: city_game.GameData.data:type_name -> city_game.TickData
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_city_game_proto_proto_init() }
func file_city_game_proto_proto_init() {
	if File_city_game_proto_proto != nil {
		return
	}
	file_city_game_proto_proto_msgTypes[3].OneofWrappers = []any{}
	file_city_game_proto_proto_msgTypes[5].OneofWrappers = []any{}
	file_city_game_proto_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_city_game_proto_proto_rawDesc), len(file_city_game_proto_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_city_game_proto_proto_goTypes,
		DependencyIndexes: file_city_game_proto_proto_depIdxs,
		EnumInfos:         file_city_game_proto_proto_enumTypes,
		MessageInfos:      file_city_game_proto_proto_msgTypes,
	}.Build()
	File_city_game_proto_proto = out.File
	file_city_game_proto_proto_goTypes = nil
	file_city_game_proto_proto_depIdxs = nil
}
