FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    openssh-server \
    python3 python3-pip python3-venv \
    build-essential gdb git curl bash vim emacs tmux tar screen ca-certificates \
 && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash troll && \
    echo "troll:bridgelover47" | chpasswd

RUN mkdir /var/run/sshd && \
    echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config && \
    echo "AllowUsers troll" >> /etc/ssh/sshd_config && \
    echo "AllowTcpForwarding yes" >> /etc/ssh/sshd_config && \
    echo "GatewayPorts yes" >> /etc/ssh/sshd_config && \
    echo "PermitTunnel yes" >> /etc/ssh/sshd_config

USER troll
WORKDIR /home/troll

COPY riddle.c .

USER root
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]

