package consts

const MANA_COST_SUMMON = 500
const MANA_COST_RELEASE = -250
const MANA_COST_SET_ACTION = 1
const MANA_REGENERATION = 50
const MANA_MAX = 2500

const GRID_WIDTH = 40
const GRID_HEIGHT = 17

const ITEM_MAX_CARRY_PICKAXE = 4
const ITEM_MAX_CARRY_BUCKET = 16
const ITEM_MAX_CARRY_PLANK = 16
const ITEM_MAX_CARRY_STONE = 16
const ITEM_MAX_CARRY_ORE = 16
const ITEM_MAX_CARRY_SANDBUCKET = 4
const ITEM_MAX_CARRY_GLASS = 4
const ITEM_MAX_CARRY_METAL = 16
const ITEM_MAX_CARRY_WINDOW = 16
const ITEM_MAX_CARRY_DOOR = 8
const ITEM_MAX_CARRY_WORKBENCH = 4
const ITEM_MAX_CARRY_FURNACE = 4
const ITEM_MAX_CARRY_CRATE = 4
const ITEM_MAX_CRATE_MULTIPLIER = 8

const HELPER_STACK_COUNT = 2
const BUILDING_STACK_COUNT_WORKBENCH = 2
const BUILDING_STACK_COUNT_FURNACE = 1
const BUILDING_STACK_COUNT_CRATE = 1

const FURNACE_SMELTING_TICKS = 4
